files:
- generatedChecksum: E45D1648EFC10229D7BE94DB19221FF7
  logicalPath: config\sam_da1_xpro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E45D1648EFC10229D7BE94DB19221FF7
- generatedChecksum: 5E4A7CACA7310332D48E36BFF06A10E9
  logicalPath: config\sam_da1_xpro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5E4A7CACA7310332D48E36BFF06A10E9
- generatedChecksum: A93DD242AFA03ABA87C7AA337EDABEEA
  logicalPath: config\sam_da1_xpro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A93DD242AFA03ABA87C7AA337EDABEEA
- generatedChecksum: 6513F2461B8F476B68CA73906086047F
  logicalPath: config\sam_da1_xpro
  name: libc_syscalls.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6513F2461B8F476B68CA73906086047F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 286408EB00691AC4B0A1A8FD8DA27373
  logicalPath: config\sam_da1_xpro\peripheral\clock
  name: plib_clock.c
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: SOURCE
  userChecksum: 286408EB00691AC4B0A1A8FD8DA27373
- generatedChecksum: DB9884A3A5B992C9084B350DC3A44198
  logicalPath: config\sam_da1_xpro\peripheral\dmac
  name: plib_dmac.c
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: DB9884A3A5B992C9084B350DC3A44198
- generatedChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
  logicalPath: config\sam_da1_xpro\peripheral\evsys
  name: plib_evsys.c
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: SOURCE
  userChecksum: C99E6D9B9BA371EA749B7DC16BC2C209
- generatedChecksum: 92F88FC32CEE461DB8BC90E7A1DB2F6F
  logicalPath: config\sam_da1_xpro\peripheral\nvic
  name: plib_nvic.c
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 92F88FC32CEE461DB8BC90E7A1DB2F6F
- generatedChecksum: DCEDF4816BCB2CB275DBB1125A07C4D8
  logicalPath: config\sam_da1_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.c
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: SOURCE
  userChecksum: DCEDF4816BCB2CB275DBB1125A07C4D8
- generatedChecksum: EEAC450426A1957FF8EB35E2509BBD32
  logicalPath: config\sam_da1_xpro\peripheral\port
  name: plib_port.c
  physicalPath: peripheral\port
  security: NON_SECURE
  type: SOURCE
  userChecksum: EEAC450426A1957FF8EB35E2509BBD32
- generatedChecksum: 4BD247541B06035665D3853E82ADF7F7
  logicalPath: config\sam_da1_xpro\peripheral\sercom\spi_master
  name: plib_sercom1_spi_master.c
  physicalPath: peripheral\sercom\spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BD247541B06035665D3853E82ADF7F7
- generatedChecksum: 2645E564BD945DAED1424FD8D7B39330
  logicalPath: config\sam_da1_xpro
  name: startup_xc32.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2645E564BD945DAED1424FD8D7B39330
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\sam_da1_xpro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: D14B46ED14C76B9CE6FE57C0E2129357
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: ac.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D14B46ED14C76B9CE6FE57C0E2129357
- generatedChecksum: B3F5A7A7409650BE9A9DCC47D4F3A394
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B3F5A7A7409650BE9A9DCC47D4F3A394
- generatedChecksum: 80FACED5BB1BFD20C6CCA6ABAED7D456
  logicalPath: packs\ATSAMDA1J16B_DFP
  name: atsamda1j16b.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 80FACED5BB1BFD20C6CCA6ABAED7D456
- generatedChecksum: 01B82424BC59A54620F7E9E0DB808EBB
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cachel1_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 01B82424BC59A54620F7E9E0DB808EBB
- generatedChecksum: 00A88E28C299A373117BC4D5B9E80C80
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 00A88E28C299A373117BC4D5B9E80C80
- generatedChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 734DF6998F09B2D22A4D9FE1D544FDFC
- generatedChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_armclang_ltm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D653BEFE5E6B1D00AB3682CE5D24C11
- generatedChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_compiler.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 60385A5C6C9882B5D30709A1F6EAEC35
- generatedChecksum: 42E8B722917508A3A9373D13AD827ED6
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_gcc.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 42E8B722917508A3A9373D13AD827ED6
- generatedChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_iccarm.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 376D5C7FD29CAA507ACB1AAB8746B1AD
- generatedChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: cmsis_version.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: 52F91AC0727F2311EDA0E3BAA7719A9F
- generatedChecksum: CCBD23918BE14943EA128B0D552031C5
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: core_cm0plus.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: CCBD23918BE14943EA128B0D552031C5
- generatedChecksum: 828D1A271A0A8B3BB21B418D93584ADB
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: dac.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 828D1A271A0A8B3BB21B418D93584ADB
- generatedChecksum: 4704B301340D29CCAF8601D88B068E95
  logicalPath: config\sam_da1_xpro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4704B301340D29CCAF8601D88B068E95
- generatedChecksum: 639D83C0D5AB8DB52D8A6DE4C3582A32
  logicalPath: config\sam_da1_xpro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 639D83C0D5AB8DB52D8A6DE4C3582A32
- generatedChecksum: 85D3482D395C59BDFF268B01940CDDDE
  logicalPath: config\sam_da1_xpro
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 85D3482D395C59BDFF268B01940CDDDE
- generatedChecksum: EBDED58446BAB238B5EA4E735FFE151A
  logicalPath: config\sam_da1_xpro
  name: device_vectors.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: EBDED58446BAB238B5EA4E735FFE151A
- generatedChecksum: 42FBC3F9F3B41637935903F73741CF4B
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: dmac.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 42FBC3F9F3B41637935903F73741CF4B
- generatedChecksum: E7B01560E4BED98E56B0192EB8BD4EDD
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: dsu.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E7B01560E4BED98E56B0192EB8BD4EDD
- generatedChecksum: E28F27B9E9BD87A0DB06C730EE36AAF8
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: eic.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E28F27B9E9BD87A0DB06C730EE36AAF8
- generatedChecksum: 6D04AABE25424BAFCAFBBB1E0FF2AB60
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: evsys.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6D04AABE25424BAFCAFBBB1E0FF2AB60
- generatedChecksum: E2C423AF2D13B5F9848361C79CF0A168
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: gclk.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E2C423AF2D13B5F9848361C79CF0A168
- generatedChecksum: 14F53880949B9DB4316887A7A5C7618C
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: hmatrixb.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 14F53880949B9DB4316887A7A5C7618C
- generatedChecksum: C8AB3CA3C9336D6232A83664BCCDEC1C
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: i2s.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C8AB3CA3C9336D6232A83664BCCDEC1C
- generatedChecksum: 807486F4D55F97DDF3B04B24C7EFCC3C
  logicalPath: config\sam_da1_xpro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 807486F4D55F97DDF3B04B24C7EFCC3C
- generatedChecksum: B96ADDA2C111E73B26EBA5E7B4498912
  logicalPath: packs\CMSIS\CMSIS\Core\Include
  name: mpu_armv7.h
  physicalPath: ..\..\packs\CMSIS\CMSIS\Core\Include
  security: NON_SECURE
  type: HEADER
  userChecksum: B96ADDA2C111E73B26EBA5E7B4498912
- generatedChecksum: F46EE8C0119EF66CE963AE557E51298E
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: mtb.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F46EE8C0119EF66CE963AE557E51298E
- generatedChecksum: CCF9F8387CAF1A8155AEA6E32EBA34FE
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: nvmctrl.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: CCF9F8387CAF1A8155AEA6E32EBA34FE
- generatedChecksum: FCEDEAB92583FEBB6099E4D693E54871
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: pac.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FCEDEAB92583FEBB6099E4D693E54871
- generatedChecksum: D9883C70E96468DEE4D7B4669D1C837B
  logicalPath: config\sam_da1_xpro\peripheral\clock
  name: plib_clock.h
  physicalPath: peripheral\clock
  security: NON_SECURE
  type: HEADER
  userChecksum: D9883C70E96468DEE4D7B4669D1C837B
- generatedChecksum: FCC42F862ABCDD8C4368470DCDAADF2E
  logicalPath: config\sam_da1_xpro\peripheral\dmac
  name: plib_dmac.h
  physicalPath: peripheral\dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: FCC42F862ABCDD8C4368470DCDAADF2E
- generatedChecksum: CCAEF942C66AF995876DFD85CEFF611F
  logicalPath: config\sam_da1_xpro\peripheral\evsys
  name: plib_evsys.h
  physicalPath: peripheral\evsys
  security: NON_SECURE
  type: HEADER
  userChecksum: CCAEF942C66AF995876DFD85CEFF611F
- generatedChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
  logicalPath: config\sam_da1_xpro\peripheral\nvic
  name: plib_nvic.h
  physicalPath: peripheral\nvic
  security: NON_SECURE
  type: HEADER
  userChecksum: 55ECCC7FA71BD15B46EF80DC0515ED7A
- generatedChecksum: 20EC1DD5FFCF7C1343D7124F3C9A640D
  logicalPath: config\sam_da1_xpro\peripheral\nvmctrl
  name: plib_nvmctrl.h
  physicalPath: peripheral\nvmctrl
  security: NON_SECURE
  type: HEADER
  userChecksum: 20EC1DD5FFCF7C1343D7124F3C9A640D
- generatedChecksum: E30875483BF153BBFB0F3122D014A6D5
  logicalPath: config\sam_da1_xpro\peripheral\port
  name: plib_port.h
  physicalPath: peripheral\port
  security: NON_SECURE
  type: HEADER
  userChecksum: E30875483BF153BBFB0F3122D014A6D5
- generatedChecksum: D3278D84519FC15D8D2EB14921A9BBFE
  logicalPath: config\sam_da1_xpro\peripheral\sercom\spi_master
  name: plib_sercom1_spi_master.h
  physicalPath: peripheral\sercom\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: D3278D84519FC15D8D2EB14921A9BBFE
- generatedChecksum: A06CFE6AEC7B18A5C3DEAC185207002C
  logicalPath: config\sam_da1_xpro\peripheral\sercom\spi_master
  name: plib_sercom_spi_master_common.h
  physicalPath: peripheral\sercom\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: A06CFE6AEC7B18A5C3DEAC185207002C
- generatedChecksum: 403E090A7F92A911064875FED5E5B12A
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: pm.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 403E090A7F92A911064875FED5E5B12A
- generatedChecksum: 575857557D0DAB5DAD185F79F9CB4D54
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: port.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 575857557D0DAB5DAD185F79F9CB4D54
- generatedChecksum: 680CB11F367F1DE88309ECBBD952A8C4
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: ptc.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 680CB11F367F1DE88309ECBBD952A8C4
- generatedChecksum: 2DBD95848E8A7E141AB0DB73DB2BC2BF
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2DBD95848E8A7E141AB0DB73DB2BC2BF
- generatedChecksum: 96EE81EBD73A957C28306A5016F248C2
  logicalPath: packs\ATSAMDA1J16B_DFP\pio
  name: samda1j16b.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 96EE81EBD73A957C28306A5016F248C2
- generatedChecksum: FF634A761537B80ADBECF232E04369B7
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: sercom.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FF634A761537B80ADBECF232E04369B7
- generatedChecksum: 45C040CA96B049CCDC56604A0FB2814E
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: sysctrl.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 45C040CA96B049CCDC56604A0FB2814E
- generatedChecksum: FAF6E859CA9979C011FCA585F4B1E20F
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FAF6E859CA9979C011FCA585F4B1E20F
- generatedChecksum: 2BDE3B5FABC6DE4EAB882A0A7DA5F58C
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: tcc.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2BDE3B5FABC6DE4EAB882A0A7DA5F58C
- generatedChecksum: 20E829A99B86C2889E4E2E536161C27A
  logicalPath: config\sam_da1_xpro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 20E829A99B86C2889E4E2E536161C27A
- generatedChecksum: 5D429A6E6B24F81F114829E317B4D824
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: usb.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D429A6E6B24F81F114829E317B4D824
- generatedChecksum: 5FE457F24465ED521ED58C3D7E505D65
  logicalPath: packs\ATSAMDA1J16B_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\ATSAMDA1J16B_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5FE457F24465ED521ED58C3D7E505D65
- generatedChecksum: 250349A258878A834D6478C345DEA281
  logicalPath: config\sam_da1_xpro
  name: ATSAMDA1J16B.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 250349A258878A834D6478C345DEA281
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_da1_xpro;../src/packs/ATSAMDA1J16B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_da1_xpro;../src/packs/ATSAMDA1J16B_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
