configName: sam_d21_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: ATSAMD21J18A
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.5.1
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.0.24\samd21a\atdf\ATSAMD21J18A.atdf
