configName: sam_d21_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMD21J18A
projectName: ''
settings:
  PackageFilter: audio;bootloader;bsp;core;core_apps_pic32cz_ca;crypto;cryptoauthlib;csp;csp_apps_sam_d21_da1;gfx;mbed_os_rtos;mbed_os_rtos_apps;micrium_ucos3;motor_control;net;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.116\samd21a\atdf\ATSAMD21J18A.atdf
